### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/VOC2008test.tar'

### ISSUE THREAD

**Issue by ruicx** [foamliu/Deep-Image-Matting#24]
Hi, when I run `pre_process.py` meet a _FileNotFoundError_ as fallow:

```
(tensorflow) ruichengxie@amax:~/jupyter2/segmentation/Deep-Image-Matting$ python pre_process.py
Extracting data/Adobe_Deep_Matting_Dataset.zip...
Extracting data/train2014.zip...
Extracting data/VOCtrainval_14-Jul-2008.tar...
Extracting data/VOC2008test.tar...
Traceback (most recent call last):
  File "pre_process.py", line 97, in <module>
    tar = tarfile.open(tar_file)
  File "/home/ruichengxie/.conda/envs/tensorflow/lib/python3.6/tarfile.py", line 1568, in open
    return func(name, "r", fileobj, **kwargs)
  File "/home/ruichengxie/.conda/envs/tensorflow/lib/python3.6/tarfile.py", line 1633, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/home/ruichengxie/.conda/envs/tensorflow/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/VOC2008test.tar'
```

The question may cause by trying to open an unexist file, 
https://github.com/foamliu/Deep-Image-Matting/blob/a5ddd97a3b941178b034d968544c709d04d3ac21/pre_process.py#L94-L99

Unfortunately, I couldn't find the download link of this file in `README` or  PASCAL VOC website. Thus, I comment those lines, and the code seems can ran.

Is _VOC2008test.tar_ necessary? Where can I get this file?

Thx.

**Comment by foamliu** [comment]
This file can be downloaded at PASCAL VOC website.

**Comment by foamliu** [comment]
![default](https://user-images.githubusercontent.com/14009435/51098112-a6910080-1803-11e9-8b47-1dd4593554d5.PNG)

**Comment by ruicx** [comment]
thanks
