### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by bobykhani** [foamliu/Deep-Image-Matting#7]
Hi, I Rebuild the Dataset But when I want to Train the model this happened:

Epoch 1/1000
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 565, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 548, in <lambda>
    initargs=(seqs,))
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 565, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 548, in <lambda>
    initargs=(seqs,))
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Bobykhani\Anaconda2\envs\tensorflow\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

Any Solution?
thx

**Comment by foamliu** [comment]
The code was tested on Linux(Ubuntu 16.04). Are you working on Windows?
